Repository openshift/check-payload, pull requests merged in 2023-07, with the labels that each got.

#51 OCPBUGS-15916: fix output on runs
  internal/scan/printer.go
Labels: jira/valid-reference, jira/invalid-bug

#55 Add golangci timeout, disable custom cache
  .golangci.yml
  Makefile
Labels: approved

#53 feat: ensure the config is fully parsed
  dist/releases/4.9/config.toml
  main.go
Labels: lgtm, approved

#54 fix: log the entire configuration
  go.mod
  go.sum
  internal/types/types_config.go
Labels: lgtm, approved

#56 Minor scanBinary cleanups
  internal/validations/validations.go
Labels: lgtm, approved

#57 ExpectedSyms: document, refactor, return bool
  internal/golang/goscan.go
  internal/validations/validations.go
Labels: lgtm, approved

#58 fix: simplify displayExceptions
  internal/scan/printer.go
Labels: lgtm, approved

#59 Make getComponent return string
  internal/scan/printer.go
Labels: lgtm, approved

#63 chore: CRW-4582 exclude ripgrep from DS 3.7...
  dist/releases/4.10/config.toml
  dist/releases/4.11/config.toml
  dist/releases/4.12/config.toml
  dist/releases/4.13/config.toml
Labels: ok-to-test, lgtm, approved

#61 add dependabot support
  .github/dependabot.yml
Labels: lgtm, approved

#70 Minor optimizations
  internal/validations/validations.go
Labels: lgtm, approved

#72 optimize using regular expressions
  internal/validations/validations.go
  internal/validations/validations_test.go
Labels: lgtm, approved

#73 feat: do not depend on go binary
  internal/golang/goscan.go
  internal/validations/validations.go
  internal/validations/validations_test.go
  main.go
Labels: lgtm, approved

#75 rpm-related refactoring and cleanups
  dist/releases/4.10/config.toml
  dist/releases/4.11/config.toml
  dist/releases/4.12/config.toml
  dist/releases/4.13/config.toml
  dist/releases/4.9/config.toml
  internal/rpm/rpm.go
  internal/scan/node_scan.go
  internal/types/types.go
  internal/types/types_config.go
Labels: lgtm, approved

#74 chore: CRW-4582 add more exceptions for known issues
  dist/releases/4.10/config.toml
  dist/releases/4.11/config.toml
  dist/releases/4.12/config.toml
  dist/releases/4.13/config.toml
Labels: ok-to-test, lgtm, approved

#77 chore: CRW-4582 exclude /usr/libexec/catatonit/catatonit in payload.devspaces-udi-rhel8-container as it's already excluded in root config.toml
  dist/releases/4.10/config.toml
  dist/releases/4.11/config.toml
  dist/releases/4.12/config.toml
  dist/releases/4.13/config.toml
Labels: ok-to-test, lgtm, approved

#78 Rpm to scan
  internal/rpm/rpm.go
  internal/scan/node_scan.go
  internal/scan/printer.go
  internal/scan/scan.go
  internal/types/types.go
  internal/types/types_scan_result.go
  internal/validations/validations.go
Labels: lgtm, approved

#79 hotfix: fix 4.9 config
  dist/releases/4.9/config.toml
Labels: lgtm, approved

#69 feat: show component, tag, rpm in logs
  internal/scan/node_scan.go
  internal/scan/scan.go
  internal/types/types_scan_result.go
Labels: lgtm, approved

#82 perf: skip all files with no x bit set
  internal/scan/node_scan.go
  internal/scan/scan.go
Labels: lgtm, approved

#83 Node scan hotfixes
  internal/rpm/rpm.go
  internal/scan/node_scan.go
Labels: lgtm, approved

#86 Ability to skip individual errors; rework configs
  Makefile
  README.md
  config.toml
  dist/releases/4.10/config.toml
  dist/releases/4.11/config.toml
  dist/releases/4.12/config.toml
  dist/releases/4.13/config.toml
  dist/releases/4.9/config.toml
  internal/scan/node_scan.go
  internal/scan/printer.go
  internal/scan/scan.go
  internal/types/error_map.go
  internal/types/errors.go
  internal/types/gen_error_map.go
  internal/types/types.go
  internal/types/types_config.go
  internal/types/types_known_error.go
  internal/validations/validations.go
  main.go
Labels: lgtm, approved

#92 feat: add dirs to per-error exclusion lists
  config.toml
  dist/releases/4.13/config.toml
  internal/types/types.go
  internal/types/types_config.go
Labels: lgtm, approved

#90 Hotfix: fix error names, configs merging
  Makefile
  dist/releases/4.10/config.toml
  dist/releases/4.13/config.toml
  dist/releases/4.9/config.toml
  internal/types/error_map.go
  internal/types/types.go
Labels: lgtm, approved

#91 test: check that embedded configs are sane
  dist/releases/config_test.go
  dist/releases/embeds.go
Labels: lgtm, approved

#88 Use debug/elf to check for dynamic binaries
  internal/validations/validations.go
  main.go
Labels: lgtm, approved

#95 Better config merge and validation
  dist/releases/config_test.go
  go.mod
  internal/types/types.go
  internal/types/types_config_file.go
  internal/types/types_config_file_test.go
  main.go
  vendor/github.com/pmezard/go-difflib/LICENSE
  vendor/github.com/pmezard/go-difflib/difflib/difflib.go
  vendor/github.com/stretchr/testify/LICENSE
  vendor/github.com/stretchr/testify/assert/assertion_compare.go
  vendor/github.com/stretchr/testify/assert/assertion_compare_can_convert.go
  vendor/github.com/stretchr/testify/assert/assertion_compare_legacy.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go.tmpl
  vendor/github.com/stretchr/testify/assert/assertion_forward.go
  vendor/github.com/stretchr/testify/assert/assertion_forward.go.tmpl
  vendor/github.com/stretchr/testify/assert/assertion_order.go
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/github.com/stretchr/testify/assert/doc.go
  vendor/github.com/stretchr/testify/assert/errors.go
  vendor/github.com/stretchr/testify/assert/forward_assertions.go
  vendor/github.com/stretchr/testify/assert/http_assertions.go
  vendor/github.com/stretchr/testify/require/doc.go
  vendor/github.com/stretchr/testify/require/forward_requirements.go
  vendor/github.com/stretchr/testify/require/require.go
  vendor/github.com/stretchr/testify/require/require.go.tmpl
  vendor/github.com/stretchr/testify/require/require_forward.go
  vendor/github.com/stretchr/testify/require/require_forward.go.tmpl
  vendor/github.com/stretchr/testify/require/requirements.go
  vendor/modules.txt
Labels: lgtm, approved

#97 OCPBUGS-17077: update(4.9): ignore files
  dist/releases/4.9/config.toml
Labels: jira/valid-reference, approved, jira/valid-bug
