Repository openshift/check-payload, pull requests merged in 2023-10, with the labels that each got.

#115 add Java / JDK image scan option
  .gitignore
  README.md
  config.toml
  dist/releases/embeds.go
  dist/releases/java/FIPS.java
  internal/podman/podman.go
  internal/scan/scan.go
  internal/types/types.go
  internal/validations/validations.go
  main.go
Labels: lgtm, approved

#121 internal/podman: add retry
  internal/podman/podman.go
Labels: lgtm, approved

#124 dockerfile: bump base to rhel 9
  Dockerfile
Labels: lgtm, approved

#125 dummy commit to rebuild images
  CHANGELOG.md
Labels: approved

#126 OCPBUGS-22678: bump builder to rhel9
  Dockerfile
Labels: jira/valid-reference, jira/severity-moderate, lgtm, approved, jira/valid-bug
