Repository openshift/check-payload, pull requests merged in 2023-08, with the labels that each got.

#101 chore(readme): add release badge
  README.md
Labels: lgtm, approved

#102 chore: add /sbin/ldconfig to ignore
  config.toml
Labels: lgtm, approved

#103 OCPNODE-1743: Implement `--rpm-scan` for payload/image, `--walk-scan` for node scans
  CHANGELOG.md
  internal/scan/node_scan.go
  internal/scan/scan.go
  internal/types/types.go
  main.go
Labels: jira/valid-reference, lgtm, approved

#106 chore: remove a dup from 4.13 config
  dist/releases/4.13/config.toml
Labels: lgtm, approved

#108 Config validation fixups
  dist/releases/config_test.go
  internal/types/types_config_file.go
Labels: lgtm, approved

#105 sort config versions for display
  CHANGELOG.md
  dist/releases/embeds.go
Labels: lgtm, approved

#109 chore(release): prep for 0.3.1 release
  CHANGELOG.md
Labels: lgtm, approved

#110 chore(config): remove cliff.toml since it is unused
  CHANGELOG.md
  cliff.toml
Labels: approved

#111 chore(Dockerfile): bump dockerfile to use golang 1.21
  Dockerfile
Labels: approved
